"""symbols.py  -- global symbols list"""

ACTIVE="ACTIVE"
ARG="ARG"
AUTHORITY="AUTHORITY"
BINDINGS="BINDINGS"
BODY="BODY"
CHANGES="CHANGES"
CONTAINS="CONTAINS"
CHILDREN="CHILDREN"
COL="COL"
COLSPAN="COLSPAN"
CREATED="CREATED"
CREATOR="CREATOR"
DATA="DATA"
DEFAULT="DEFAULT"
DEPTH="DEPTH"
DESCRIPTION="DESCRIPTION"
DICT="DICT"
DIR="DIR"
FACET="FACET"
FN="FN"
GETLINE="GETLINE"
HANDLE="HANDLE"
HEIGHT="HEIGHT"
HOOK="HOOK"
HORZ="HORZ"
ID="ID"
INDENT="INDENT"
KEY="KEY"
KIND="KIND"
LASTNONSCROLLBAR="LASTNONSCROLLBAR"
LEFT="LEFT"
LINK="LINK"
LN="LN"
LNNO="LNNO"
LOOP="LOOP"
MAP="MAP"  # not used yet
MAPPING="MAPPING"
MAPS="MAPS"  # not used yet
MAPSEARCH="MAPSEARCH"  # not used yet
MNEMONICS="MNEMONICS"
NAME="NAME"
NEXTID="NEXTID"
NEW="NEW"
NODE="NODE"
NOTEBOOK="NOTEBOOK"
OLD="OLD"
ORD="ORD"
PARENT="PARENT"
PARTS="PARTS"
PATTERN="PATTERN"
PROJ="PROJ"
RAW="RAW"
REC="REC"  # short for "record"
RECTYPE="RECTYPE"  # short for "record type"
REGISTRY="REGISTRY"
REQUEST="REQUEST"
RESULT="RESULT"
RIGHT="RIGHT"
ROW="ROW"
ROWSPAN="ROWSPAN"
RW="RW"
SCHEMA="SCHEMA"
SEL="SEL"
SETLINE="SETLINE"
SETTINGS="SETTINGS"
STATUS="STATUS"
STICKY="STICKY"
STR="STR"
STRLIST="STRLIST"
TAG="TAG"
TAGS="TAGS"
TAGSEARCH="TAGSEARCH"
TCL="TCL"
TEXT="TEXT"
TITLE="TITLE"
TODO="TODO"
TKNAME="TKNAME"
TYPE="TYPE"
UNIQUE="UNIQUE"
UPDATE="UPDATE"
USER="USER"
VAR="VAR"
VARDEFAULT="VARDEFAULT"
VERT="VERT"
WIDTH="WIDTH"
WITH="WITH"


# Tk Window Types

FRAME="FRAME"
LABELFRAME="LABELFRAME"
LABEL="LABEL"
BUTTON="BUTTON"
ENTRY="ENTRY"
CHECKBUTTON="CHECKBUTTON"
LISTBOX="LISTBOX"
TEXT="TEXT"
CANVAS="CANVAS"
TREE="TREE"
SCROLLBAR="SCROLLBAR"


# listdict.py

EQ="EQ"  # equal to
NEQ="NEQ"  # not equal to
GT="GT"  # greater than
LT="LT"  # less than
GTE="GTE"  # greater than or equal to
LTE="LTE"  # less than or equal to
CONTAINS="CONTAINS"  # sub-collection contains item
NCONTAINS="NCONTAINS"  # sub-collection does NOT contain item
WITHIN="WITHIN"  # value within collection
NWITHIN="NWITHIN"  # value NOT within collection

